// Code generated by Slice Machine. DO NOT EDIT.

import Code from './Code';
import ContactForm from './ContactForm';
import Image from './Image';
import Quote from './Quote';
import Text from './Text';

export {
	Code,
	ContactForm,
	Image,
	Quote,
	Text,
};

export const components = {
	code: Code,
	contact_form: ContactForm,
	image: Image,
	quote: Quote,
	text: Text,
};
